# Generated by Django 3.2.3 on 2021-05-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muggum', '0002_auto_20210528_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='mug',
            name='firstname',
            field=models.CharField(max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='mug',
            name='lastname',
            field=models.CharField(max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='realisedproject',
            name='energy',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reallife',
            name='energy',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realskill',
            name='energy',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mug',
            name='job',
            field=models.CharField(max_length=31, null=True),
        ),
    ]
