# Generated by Django 3.2.3 on 2021-05-14 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('head', 'Head'), ('body_start', 'Body (Start)'), ('body_end', 'Body (End)')], max_length=255)),
                ('js_code', models.TextField(max_length=4095)),
            ],
        ),
        migrations.CreateModel(
            name='PaidShapeApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('token_or_version', models.CharField(max_length=255)),
                ('integrity', models.TextField(max_length=4095)),
                ('dashboard_url', models.URLField()),
                ('easy_api', models.CharField(choices=[('bootstrap', 'Bootstrap (DeliverJS)'), ('fontawesome', 'FontAwesome'), ('leaflet', 'Leaflet')], max_length=255)),
                ('js_code', models.TextField(max_length=4095, null=True)),
                ('readme', models.TextField(max_length=4095)),
                ('date_buy', models.DateField()),
                ('date_expiration', models.DateField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreeShapeApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('token_or_version', models.CharField(max_length=255)),
                ('integrity', models.TextField(max_length=4095)),
                ('dashboard_url', models.URLField()),
                ('easy_api', models.CharField(choices=[('bootstrap', 'Bootstrap (DeliverJS)'), ('fontawesome', 'FontAwesome'), ('leaflet', 'Leaflet')], max_length=255)),
                ('js_code', models.TextField(max_length=4095, null=True)),
                ('readme', models.TextField(max_length=4095)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CloudShapeApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('token_or_version', models.CharField(max_length=255)),
                ('integrity', models.TextField(max_length=4095)),
                ('dashboard_url', models.URLField()),
                ('easy_api', models.CharField(choices=[('bootstrap', 'Bootstrap (DeliverJS)'), ('fontawesome', 'FontAwesome'), ('leaflet', 'Leaflet')], max_length=255)),
                ('js_code', models.TextField(max_length=4095, null=True)),
                ('readme', models.TextField(max_length=4095)),
                ('price', models.PositiveIntegerField()),
                ('per', models.CharField(choices=[('day', 'Jour'), ('month', 'Mois'), ('year', 'Année')], max_length=11)),
                ('date_start', models.DateField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
