# Generated by Django 3.2.3 on 2021-05-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('html_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudshapeapi',
            name='dashboard_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='freeshapeapi',
            name='dashboard_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='paidshapeapi',
            name='dashboard_url',
            field=models.URLField(null=True),
        ),
    ]
